// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: tracker_to_tracker.proto

package tracker_tracker_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RePublishQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InfoHash []byte `protobuf:"bytes,1,opt,name=infoHash,proto3" json:"infoHash,omitempty"`
	PeerID   string `protobuf:"bytes,2,opt,name=peerID,proto3" json:"peerID,omitempty"`
	IP       string `protobuf:"bytes,3,opt,name=IP,proto3" json:"IP,omitempty"`
	Port     int32  `protobuf:"varint,4,opt,name=Port,proto3" json:"Port,omitempty"`
}

func (x *RePublishQuery) Reset() {
	*x = RePublishQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracker_to_tracker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RePublishQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RePublishQuery) ProtoMessage() {}

func (x *RePublishQuery) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_to_tracker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RePublishQuery.ProtoReflect.Descriptor instead.
func (*RePublishQuery) Descriptor() ([]byte, []int) {
	return file_tracker_to_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *RePublishQuery) GetInfoHash() []byte {
	if x != nil {
		return x.InfoHash
	}
	return nil
}

func (x *RePublishQuery) GetPeerID() string {
	if x != nil {
		return x.PeerID
	}
	return ""
}

func (x *RePublishQuery) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *RePublishQuery) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RePublishResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RePublishResponse) Reset() {
	*x = RePublishResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracker_to_tracker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RePublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RePublishResponse) ProtoMessage() {}

func (x *RePublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_to_tracker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RePublishResponse.ProtoReflect.Descriptor instead.
func (*RePublishResponse) Descriptor() ([]byte, []int) {
	return file_tracker_to_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *RePublishResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type KnowMeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RedKey string `protobuf:"bytes,1,opt,name=redKey,proto3" json:"redKey,omitempty"`
	IP     string `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Port   int32  `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
}

func (x *KnowMeRequest) Reset() {
	*x = KnowMeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracker_to_tracker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KnowMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowMeRequest) ProtoMessage() {}

func (x *KnowMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_to_tracker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowMeRequest.ProtoReflect.Descriptor instead.
func (*KnowMeRequest) Descriptor() ([]byte, []int) {
	return file_tracker_to_tracker_proto_rawDescGZIP(), []int{2}
}

func (x *KnowMeRequest) GetRedKey() string {
	if x != nil {
		return x.RedKey
	}
	return ""
}

func (x *KnowMeRequest) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *KnowMeRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type KnowMeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	RepeatInterval int32 `protobuf:"varint,2,opt,name=repeatInterval,proto3" json:"repeatInterval,omitempty"`
}

func (x *KnowMeResponse) Reset() {
	*x = KnowMeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracker_to_tracker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KnowMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowMeResponse) ProtoMessage() {}

func (x *KnowMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_to_tracker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowMeResponse.ProtoReflect.Descriptor instead.
func (*KnowMeResponse) Descriptor() ([]byte, []int) {
	return file_tracker_to_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *KnowMeResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *KnowMeResponse) GetRepeatInterval() int32 {
	if x != nil {
		return x.RepeatInterval
	}
	return 0
}

var File_tracker_to_tracker_proto protoreflect.FileDescriptor

var file_tracker_to_tracker_proto_rawDesc = []byte{
	0x0a, 0x18, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x5f, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x22, 0x68, 0x0a, 0x0e, 0x52, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x66, 0x6f, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x69, 0x6e, 0x66, 0x6f, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x2b, 0x0a,
	0x11, 0x52, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4b, 0x0a, 0x0d, 0x4b, 0x6e,
	0x6f, 0x77, 0x4d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x64, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x64,
	0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x50, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x50, 0x0a, 0x0e, 0x4b, 0x6e, 0x6f, 0x77, 0x4d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61,
	0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x32, 0x96, 0x01, 0x0a, 0x13, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x42, 0x0a, 0x09, 0x52, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x17,
	0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x1a, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x06, 0x4b, 0x6e, 0x6f, 0x77, 0x4d, 0x65, 0x12,
	0x16, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x4b, 0x6e, 0x6f, 0x77, 0x4d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x2e, 0x4b, 0x6e, 0x6f, 0x77, 0x4d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x1c, 0x5a, 0x1a, 0x2e, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x5f,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tracker_to_tracker_proto_rawDescOnce sync.Once
	file_tracker_to_tracker_proto_rawDescData = file_tracker_to_tracker_proto_rawDesc
)

func file_tracker_to_tracker_proto_rawDescGZIP() []byte {
	file_tracker_to_tracker_proto_rawDescOnce.Do(func() {
		file_tracker_to_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(file_tracker_to_tracker_proto_rawDescData)
	})
	return file_tracker_to_tracker_proto_rawDescData
}

var file_tracker_to_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tracker_to_tracker_proto_goTypes = []interface{}{
	(*RePublishQuery)(nil),    // 0: tracker.RePublishQuery
	(*RePublishResponse)(nil), // 1: tracker.RePublishResponse
	(*KnowMeRequest)(nil),     // 2: tracker.KnowMeRequest
	(*KnowMeResponse)(nil),    // 3: tracker.KnowMeResponse
}
var file_tracker_to_tracker_proto_depIdxs = []int32{
	0, // 0: tracker.TrackerComunication.RePublish:input_type -> tracker.RePublishQuery
	2, // 1: tracker.TrackerComunication.KnowMe:input_type -> tracker.KnowMeRequest
	1, // 2: tracker.TrackerComunication.RePublish:output_type -> tracker.RePublishResponse
	3, // 3: tracker.TrackerComunication.KnowMe:output_type -> tracker.KnowMeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tracker_to_tracker_proto_init() }
func file_tracker_to_tracker_proto_init() {
	if File_tracker_to_tracker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tracker_to_tracker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RePublishQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tracker_to_tracker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RePublishResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tracker_to_tracker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KnowMeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tracker_to_tracker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KnowMeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tracker_to_tracker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracker_to_tracker_proto_goTypes,
		DependencyIndexes: file_tracker_to_tracker_proto_depIdxs,
		MessageInfos:      file_tracker_to_tracker_proto_msgTypes,
	}.Build()
	File_tracker_to_tracker_proto = out.File
	file_tracker_to_tracker_proto_rawDesc = nil
	file_tracker_to_tracker_proto_goTypes = nil
	file_tracker_to_tracker_proto_depIdxs = nil
}
